version: '3'

services:
  app:
    build: .
    command: jupyter notebook --allow-root --port=8888 --no-browser --ip=0.0.0.0
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./src:/app
